config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :users 
  root "users#index"
  resources :books

  get 'page_one', to: 'users#page_one'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user 
end

app/models/city.rb
class City < ApplicationRecord
	include ForService
end

app/models/concerns/Invoice_creator.rb
module InvoiceCreator
  extend ActiveSupport::Concern
  TAX_FEE = 0.5

  class << self
    def good_services
      puts "The Service is #{self.class}" 
    end
  end


 
  def self.generate
    puts "Don't worry! I'll generate the invoice for you at #{TAX_FEE}%"
  end
 
  def invoice_total
    puts "I'll return the invoice total"
  end
end

app/models/concerns/for_service.rb
module ForService
  extend ActiveSupport::Concern

	def self.what_service  
	  	self.class.limit(10)
	  	  puts "#{@user} hai sare"
	end

  def get_10 # Instance Method
    puts "This is instance method #{self.class}"
    self.limit(10)
  end

  def get_1
  	puts 'this is get'
  end

end

app/models/concerns/indore.rb
module Indore

	def abc
		puts User.pluck(:name).last(5)
	end
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
  # include InvoiceCreator
  include ForService

  belongs_to :user
  # resourcify
end

app/models/user.rb
class User < ApplicationRecord

  
  extend ForService

  include Indore
  extend Indore

  has_many :books 
  has_many :exercises
  accepts_nested_attributes_for :exercises
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @user = User.find(params[:id])
  end 
  def create
    @user = User.find(params[:book][:user_id])
    @user.books.create(book_name: params[:book][:book_name])  
    #redirect_to user_path 
    render :new
  end 
end

app/controllers/concerns/bhopal.rb
module Bhopal 
	def hello
		Puts User.last.name
	end

	def read_user
  	User.last(5)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    include Bhopal

    def page_one
      @users = read_user
    end

    def index
        @users = User.all
        @exercises = Exercise.all
    end

    def new
        @user = User.new
        @user.exercises.build
        @cities = City.all
    end

    def create
        @user = User.create(user_params)
        redirect_to root_path
    end

     private

     def user_params
       params.require(:user).permit(:name, :city_name, exercises_attributes: [ :id, :exercise_name])
     end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/books/new.html.erb
<br><br>

<%#= form_for Book.new do |form| %>
<%#= form.hidden_field :user_id, value: @user.id %>
    <%#= form.text_field :book_name %> 
    <%#= form.submit %>
<%# end %>

<%= form_for Book.new do |form| %>
    
    <%= form.hidden_field :user_id, value: @user.id %>
    <p>
      <%= form.label :book_name %><br>
      <%= form.text_field :book_name %>
    </p>
    
    <p>
      <%= form.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBootstrap4Integration</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_exercise.html.erb
<div class="nested-fields">
    <div class="container">
        <div class="field form-group">
            <%= f.label :exercise_name %>
            <%= f.text_field :exercise_name, class:"form-control",placeholder:"Exercise_Name" %>
        </div>
    </div>
</div>

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |f| %>
	<div class="container">
	   <div class="field form-group">
		  <%= f.label :name %><br>
		  <%= f.text_field :name ,class:"form-control",placeholder:"Name" %><br>
	   </div>
	   <div class="field form-group">
		  <%= f.label :city_name %><br>
		  <%= f.text_field :city_name ,class:"form-control",placeholder:"City Name" %><br>
	   </div>
	   <h3>Exercises:</h3>
	   <%= f.fields_for :exercises do |exercises_form| %>
		<%= render "exercise", f: exercises_form %>
	   <% end %>
	   <%= f.submit class: "btn btn-primary"  %>
	</div>
<% end %>

app/views/users/edit.html.erb
<br><br>
<%= render 'form' %>

app/views/users/index.html.erb
<h2 style="text-align: center;"><%= link_to "new one ", new_user_path %></h2>
<table class="table table-striped table-bordered table-hover friend_list">
    <thead class="thead-dark">
        <tr>
            <th>Name</th>
            <th>City Name</th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
            <tr class="size">
                <td><%= user.name %></td>
                <td><%= user.city_name %></td>
            </tr>
        <% end%>
    </tbody>
</table>
<br><br><br>

<table class="table table-striped table-bordered table-hover friend_list">
    <thead class="thead-dark">
        <tr>
            <th>Exercise Name</th>
        </tr>
    </thead>
    <tbody>
        <% @exercises.each do |exer| %>
            <tr class="size">
                <td><%= exer.exercise_name %></td>
            </tr>
        <% end%>
    </tbody>
</table>


<%= link_to 'show users', page_one_path %>

app/views/users/new.html.erb
<br><br>
<%= render 'form'%>

app/views/users/page_one.html.erb
<table class="table table-striped table-bordered table-hover friend_list">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |exer| %>
      <tr class="size">
        <td><%= exer.name %></td>
      </tr>
    <% end%>
  </tbody>
</table>

app/views/users/show.html.erb
<br><br>
Name => <%= @user.name %> <br>
City => <%= @user.city_name %>
Book_Name => <%#= @user.books.book_name %>
<h3><%= link_to 'edit user', edit_user_path %></h3>
<h2><%= link_to 'Delete', user_path, method: :delete, data: {confirm: "are u sure"} %> </h2> 
<h4><%= link_to 'new', new_user_path %></h4>

app/views/videos/_js.html.erb
<%= javascript_pack_tag 'first' %>
<%= javascript_pack_tag 'second' %>
<%= javascript_pack_tag 'third' %>

app/views/videos/index.html.erb
<h1 id="a">Videos#index</h1>
<p id="b">Find me in app/views/videos/index.html.erb</p>
<h1 id="c">i am third</h1>

<%= render 'js' %>